image: docker

services:
  - docker:dind

before_script:
  - export
  - docker login registry.gitlab.com -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

build:
  script:
    - docker pull registry.gitlab.com/user/flatris:latest || true
    - docker build . -t registry.gitlab.com/user/flatris:$CI_COMMIT_SHORT_SHA -t registry.gitlab.com/user/flatris:latest --cache-from registry.gitlab.com/user/flatris:latest
    - docker push registry.gitlab.com/user/flatris:latest
    - docker push registry.gitlab.com/user/flatris:$CI_COMMIT_SHORT_SHA
